import datetime
import json
import os
import os.path
import pickle
import time

import requests

from datetime import datetime

from pyinstalive import helpers

from . import logger
from . import globals
from . import api
from .constants import Constants

class Session:
    def _load_cookies(self, filepath):
        jar = requests.cookies.RequestsCookieJar()
        try:
            with open(filepath, 'r') as f:
                content = f.read().strip()

            if content.startswith('[') or content.startswith('{'):
                cookies_data = json.loads(content)
                if isinstance(cookies_data, dict):
                    cookies_data = [cookies_data]
                for cookie in cookies_data:
                    jar.set(
                        cookie.get('name', ''),
                        cookie.get('value', ''),
                        domain=cookie.get('domain', '.instagram.com'),
                        path=cookie.get('path', '/'),
                        expires=cookie.get('expirationDate'),
                        secure=cookie.get('secure', True)
                    )
            else:
                for line in content.split('\n'):
                    if line.startswith('#') or not line.strip():
                        continue
                    fields = line.strip().split('\t')
                    if len(fields) >= 7:
                        jar.set(
                            fields[5],
                            fields[6],
                            domain=fields[0],
                            path=fields[2] if fields[2] else '/',
                            expires=int(fields[4]) if fields[4] and fields[4].isdigit() else None,
                            secure=fields[3] == 'TRUE'
                        )
            return jar
        except FileNotFoundError:
            logger.error("Cookie file not found: {:s}".format(filepath))
            return None
        except json.JSONDecodeError:
            logger.error("Invalid JSON format in cookie file: {:s}".format(filepath))
            return None
        except Exception as e:
            logger.error("Failed to load cookie file: {:s}".format(str(e)))
            return None

    def export_cookies(self, filepath=None):
        if filepath is None:
            filepath = os.path.join(os.path.dirname(globals.config.config_path), "{}_cookies.txt".format(self.username))
        try:
            with open(filepath, 'w') as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# This file was generated by PyInstaLive\n\n")
                for cookie in self.session.cookies:
                    f.write("{}\t".format(cookie.domain))
                    f.write("TRUE\t" if cookie.domain.startswith('.') else "FALSE\t")
                    f.write("{}\t".format(cookie.path))
                    f.write("TRUE\t" if cookie.secure else "FALSE\t")
                    f.write("{}\t".format(cookie.expires if cookie.expires else ''))
                    f.write("{}\t".format(cookie.name))
                    f.write("{}\n".format(cookie.value))
            logger.info("Cookies exported to: {:s}".format(filepath))
            return filepath
        except Exception as e:
            logger.error("Failed to export cookies: {:s}".format(str(e)))
            return None
    def _save_session(self):
        with open(self.session_file, "wb") as f:
            pickle.dump(self.session, f)

    def _load_session(self):
        with open(self.session_file, "rb") as f:
            return pickle.load(f)

    def __init__(self, username, password):
        self.username = username
        self.password = password
        self.session_file = None
        self.session = None
        self.cookies = None
        self.expires_epoch = None
        self.proxy = None

    def authenticate(self, username=None, password=None, cookie_file=None):
        try:
            if globals.config.proxy and not self.proxy:
                logger.binfo("Checking if the proxy is working.")
                self.proxy = helpers.test_proxy()
                if self.proxy:
                    logger.info("The proxy is working properly.")
                else:
                    logger.warn("The proxy check failed, falling back to default connection.")
                logger.separator()

            login_success = False
            if username and password:
                self.username = username
                self.password = password
                logger.binfo("The default login credentials have been overridden.")
                logger.separator()
            
            self.session_file = os.path.join(os.path.dirname(globals.config.config_path), "{}.dat".format(self.username))

            if cookie_file:
                logger.info("Attempting to login using cookie file: {:s}".format(cookie_file))
                cookie_jar = self._load_cookies(cookie_file)
                if cookie_jar is None:
                    logger.separator()
                    return False

                sessionid = None
                for cookie in cookie_jar:
                    if cookie.name == "sessionid":
                        sessionid = cookie.value
                        break

                if not sessionid:
                    logger.error("No sessionid cookie found in cookie file.")
                    logger.separator()
                    return False

                self.session = requests.Session()
                self.session.headers = Constants.BASE_HEADERS
                self.session.headers.update({"x-csrftoken": cookie_jar.get("csrftoken", "")})

                if globals.config.proxy and self.proxy:
                    self.session.proxies = self.proxy

                self.session.cookies = cookie_jar

                login_state = api.get_login_state()

                if login_state is None:
                    logger.error("Could not verify login state. Instagram may be blocking the request.")
                    logger.error("Try using a different network or updating your cookies.")
                    logger.separator()
                    return False

                entry_data = login_state.get("entry_data", {})

                if entry_data.get("Challenge"):
                    logger.separator()
                    logger.error("The cookie session was flagged as suspicious by Instagram.")
                    logger.error("Complete the security checkpoint on Instagram and export new cookies.")
                    logger.separator()
                    return False

                if not entry_data.get("Login"):
                    logger.error("The cookie session is no longer valid.")
                    logger.error("Please export new cookies from your browser.")
                    logger.separator()
                    return False

                for cookie in list(self.session.cookies):
                    if cookie.name == "csrftoken":
                        self.expires_epoch = cookie.expires
                        break

                if self.expires_epoch is None:
                    self.expires_epoch = int(time.time()) + (90 * 24 * 60 * 60)

                login_success = True
                logger.info("Successfully logged in using cookie file.")

            elif not os.path.isfile(self.session_file):
                logger.warn("Could not find an existing login session file: {:s}".format(os.path.basename(self.session_file)))
                logger.warn("A new login session file will be created upon successful login.")

                self.session = requests.Session()
                self.session.headers = Constants.BASE_HEADERS

                if globals.config.proxy and self.proxy:
                    self.session.proxies = self.proxy

                self.session.headers.update({"x-csrftoken": api.get_csrf_token()})

                login_result = api.do_login()
                if login_result.get("authenticated", None):
                    self._save_session()
                    logger.separator()
                    logger.info("Successfully created a new login session file: {:s}".format(os.path.basename(self.session_file)))
                    for cookie in list(self.session.cookies):
                        if cookie.name == "csrftoken":
                            self.expires_epoch = cookie.expires
                    login_success = True
                else:
                    logger.separator()
                    if login_result.get("user") == False:
                        logger.error("Could not login: The account does not exist.")
                    elif login_result.get("message", '') == "checkpoint_required":
                        logger.error("Could not login: The action was flagged as suspicious by Instagram.")
                        logger.error("Complete the security checkpoint on another device and try again.")
                    else:
                        logger.error("Could not login: Ensure your credentials are correct and try again.")
                    logger.separator()
                    login_success = False
            else:
                self.session = self._load_session()
                if globals.config.proxy and self.proxy:
                    self.session.proxies = self.proxy
                logger.info("An existing login session file was found: {}".format(os.path.basename(self.session_file)))
                logger.info("Checking the validity of the saved login session.")

                for cookie in list(self.session.cookies):
                    if cookie.name == "csrftoken":
                        self.expires_epoch = cookie.expires

                if int(self.expires_epoch) <= int(time.time()):
                    os.remove(self.session_file)
                    self.session_file = None

                    logger.warn("The login session file has expired and has been deleted.")
                    logger.warn("A new login session file will be created upon successful login.")

                    time.sleep(1)
                    self.authenticate(username, password, cookie_file)
                    return
                else:
                    login_state = api.get_login_state()
                    if login_state.get("entry_data", {}) != {}:
                        if login_state.get("entry_data", {}).get("Challenge", None) != None:
                            logger.separator()
                            logger.error("The session was flagged as suspicious by Instagram.")
                            logger.error("Complete the security checkpoint on another device and try again.")
                            logger.separator()
                            login_success = False
                        else:
                            logger.error("The login session file is no longer valid.")
                            logger.error("Unspecified error. Delete the login session file and try again.")
                            logger.separator()
                            login_success = False
                    else:
                        login_success = True

            if login_success:
                if self.session.cookies["csrftoken"] != self.session.headers.get("x-csrftoken"):
                    self.session.cookies.set("csrftoken", self.session.headers.get("x-csrftoken"), domain=".instagram.com", expires=self.expires_epoch)
                logger.separator()
                logger.info('Successfully logged in using account: {:s}'.format(str(self.username)))

                expiry_date = datetime.fromtimestamp(self.expires_epoch).strftime('%m-%d-%Y at %I:%M:%S %p')
                logger.info("The login session file will expire on: {:s}".format(expiry_date))

                logger.separator()
                return True
            else:
                return False
        except Exception as e:
            logger.error('Could not login: {:s}'.format(str(e)))
            logger.separator()
            return False
        except KeyboardInterrupt:
            logger.separator()
            logger.binfo('The process was aborted by the user.')
            logger.separator()
            return False